server:
  port: 9001
spring:
  application:
    name: train-member
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.233.137:3307/train_member?serverTimezone=Asia/Shanghai
    username: root #train_member
    password: 123456
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
