server:
  port: 9000
spring:
  application:
    name: train-gateway
  cloud:
    gateway:
      routes:
        - id: train-member
          uri: http://localhost:9001 #lb://train-member
          predicates:
            - Path=/member/**
        - id: train-passenger
          uri: http://localhost:9001
          predicates:
            - Path=/passenger/**
        - id: train-business
          uri: http://localhost:9002
          predicates:
            - Path=/business/**
        - id: train-batch
          uri: http://localhost:9003
          predicates:
            - Path=/batch/**
      # 跨域
      globalcors:
        cors-configurations:
          '[/**]':
            # 允许请求的来源
            allowedOriginPatterns: "*"
            # 允许请求中携带的头信息
            allowedHeaders: "*"
            # 运行跨域的请求方式
            allowedMethods: "*"
            # 是否允许携带cookie
            allow-credentials: true
            # 跨域检测的有效期,单位s
            maxAge: 36000